author: '千夏' # 作者名称
author_avatar: '/blog/static/img/icon.png' # 作者头像
author_text: '是个飞舞，头像都是偷SuperSkidder的' # 作者信息
social: # 社交链接
  - title: '首页'
    icon: 'home'
    link: 'https://L0serQianXia.github.io/blog'
  - title: '邮件'
    icon: 'envelope'
    link: 'mailto:qianxia2333@qq.com'
  - title: 'Github'
    icon: 'github'
    link: 'https://github.com/L0serQianXia'
background: '/blog/static/img/Background.jpg' # 主题背景
menu: # 页眉菜单项目
  '关于我': /about
  '朋友们': /friends
  '小游戏': /games
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: true # 自动切换夜间模式
sidebar_rss:
  link: atom.xml