author: '千夏' # 作者名称
author_avatar: '/blog/static/img/icon.png' # 作者头像
author_text: '是个飞舞，头像都是偷SuperSkidder的' # 作者信息
social: # 社交链接
  - title: 'Github'
    icon: 'github'
    link: 'https://github.com/L0serQianXia'
  - title: '首页'
    icon: 'home'
    link: 'https://L0serQianXia.github.io/blog'
background: 'https://i.loli.net/2018/04/19/5ad840133c288.jpg' # 主题背景
menu: # 页眉菜单项目
  '关于我': /2024/02/15/about/
  '朋友们': /2024/02/15/friends/
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: true # 自动切换夜间模式
